// AUTO-GENERATED BY WEBIZEN-COMPONENT-HARVESTER
// These components wrap Shoelace Custom Elements in Dioxus macros.

#![allow(non_snake_case)]
use dioxus::prelude::*;
use core::option::Option;

/// Dioxus wrapper for `sl-alert`
#[component]
pub fn SlAlert(
    dependencies: Option<String>,
    autoHideTimeout: Option<f64>,
    remainingTimeInterval: Option<f64>,
    countdownAnimation: Option<String>,
    hasSlotController: Option<String>,
    localize: Option<String>,
    currentToastStack: Option<String>,
    toastStack: Option<String>,
    base: Option<String>,
    countdownElement: Option<String>,
    open: Option<bool>,
    closable: Option<bool>,
    variant: Option<String>,
    duration: Option<String>,
    countdown: Option<String>,
    remainingTime: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-alert {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "autoHideTimeout": autoHideTimeout.unwrap_or_default(),
            "remainingTimeInterval": remainingTimeInterval.unwrap_or_default(),
            "countdownAnimation": countdownAnimation.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "currentToastStack": currentToastStack.unwrap_or_default(),
            "toastStack": toastStack.unwrap_or_default(),
            "base": base.unwrap_or_default(),
            "countdownElement": countdownElement.unwrap_or_default(),
            "open": open.unwrap_or_default(),
            "closable": closable.unwrap_or_default(),
            "variant": variant.unwrap_or_default(),
            "duration": duration.unwrap_or_default(),
            "countdown": countdown.unwrap_or_default(),
            "remainingTime": remainingTime.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-animated-image`
#[component]
pub fn SlAnimatedImage(
    dependencies: Option<String>,
    animatedImage: Option<String>,
    frozenFrame: Option<String>,
    isLoaded: Option<bool>,
    src: Option<String>,
    alt: Option<String>,
    play: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-animated-image {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "animatedImage": animatedImage.unwrap_or_default(),
            "frozenFrame": frozenFrame.unwrap_or_default(),
            "isLoaded": isLoaded.unwrap_or_default(),
            "src": src.unwrap_or_default(),
            "alt": alt.unwrap_or_default(),
            "play": play.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-animation`
#[component]
pub fn SlAnimation(
    animation: Option<String>,
    hasStarted: Option<bool>,
    defaultSlot: Option<String>,
    name: Option<String>,
    play: Option<bool>,
    delay: Option<f64>,
    direction: Option<String>,
    duration: Option<f64>,
    easing: Option<String>,
    endDelay: Option<f64>,
    fill: Option<String>,
    iterations: Option<String>,
    iterationStart: Option<f64>,
    keyframes: Option<String>,
    playbackRate: Option<f64>,
    currentTime: Option<String>,
    handleAnimationFinish: Option<String>,
    handleAnimationCancel: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-animation {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "animation": animation.unwrap_or_default(),
            "hasStarted": hasStarted.unwrap_or_default(),
            "defaultSlot": defaultSlot.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "play": play.unwrap_or_default(),
            "delay": delay.unwrap_or_default(),
            "direction": direction.unwrap_or_default(),
            "duration": duration.unwrap_or_default(),
            "easing": easing.unwrap_or_default(),
            "endDelay": endDelay.unwrap_or_default(),
            "fill": fill.unwrap_or_default(),
            "iterations": iterations.unwrap_or_default(),
            "iterationStart": iterationStart.unwrap_or_default(),
            "keyframes": keyframes.unwrap_or_default(),
            "playbackRate": playbackRate.unwrap_or_default(),
            "currentTime": currentTime.unwrap_or_default(),
            "handleAnimationFinish": handleAnimationFinish.unwrap_or_default(),
            "handleAnimationCancel": handleAnimationCancel.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-avatar`
#[component]
pub fn SlAvatar(
    dependencies: Option<String>,
    hasError: Option<bool>,
    image: Option<String>,
    label: Option<String>,
    initials: Option<String>,
    loading: Option<String>,
    shape: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-avatar {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "hasError": hasError.unwrap_or_default(),
            "image": image.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "initials": initials.unwrap_or_default(),
            "loading": loading.unwrap_or_default(),
            "shape": shape.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-badge`
#[component]
pub fn SlBadge(
    variant: Option<String>,
    pill: Option<bool>,
    pulse: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-badge {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "variant": variant.unwrap_or_default(),
            "pill": pill.unwrap_or_default(),
            "pulse": pulse.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-breadcrumb`
#[component]
pub fn SlBreadcrumb(
    dependencies: Option<String>,
    localize: Option<String>,
    separatorDir: Option<String>,
    defaultSlot: Option<String>,
    separatorSlot: Option<String>,
    label: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-breadcrumb {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "separatorDir": separatorDir.unwrap_or_default(),
            "defaultSlot": defaultSlot.unwrap_or_default(),
            "separatorSlot": separatorSlot.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-button`
#[component]
pub fn SlButton(
    dependencies: Option<String>,
    formControlController: Option<String>,
    hasSlotController: Option<String>,
    localize: Option<String>,
    button: Option<String>,
    hasFocus: Option<bool>,
    invalid: Option<bool>,
    title: Option<String>,
    variant: Option<String>,
    size: Option<String>,
    caret: Option<bool>,
    disabled: Option<bool>,
    loading: Option<bool>,
    outline: Option<bool>,
    pill: Option<bool>,
    circle: Option<bool>,
    r#type: Option<String>,
    name: Option<String>,
    value: Option<String>,
    href: Option<String>,
    target: Option<String>,
    rel: Option<String>,
    download: Option<String>,
    form: Option<String>,
    formAction: Option<String>,
    formEnctype: Option<String>,
    formMethod: Option<String>,
    formNoValidate: Option<bool>,
    formTarget: Option<String>,
    validity: Option<String>,
    validationMessage: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-button {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "formControlController": formControlController.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "button": button.unwrap_or_default(),
            "hasFocus": hasFocus.unwrap_or_default(),
            "invalid": invalid.unwrap_or_default(),
            "title": title.unwrap_or_default(),
            "variant": variant.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "caret": caret.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "loading": loading.unwrap_or_default(),
            "outline": outline.unwrap_or_default(),
            "pill": pill.unwrap_or_default(),
            "circle": circle.unwrap_or_default(),
            "type": r#type.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "href": href.unwrap_or_default(),
            "target": target.unwrap_or_default(),
            "rel": rel.unwrap_or_default(),
            "download": download.unwrap_or_default(),
            "form": form.unwrap_or_default(),
            "formAction": formAction.unwrap_or_default(),
            "formEnctype": formEnctype.unwrap_or_default(),
            "formMethod": formMethod.unwrap_or_default(),
            "formNoValidate": formNoValidate.unwrap_or_default(),
            "formTarget": formTarget.unwrap_or_default(),
            "validity": validity.unwrap_or_default(),
            "validationMessage": validationMessage.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-breadcrumb-item`
#[component]
pub fn SlBreadcrumbItem(
    hasSlotController: Option<String>,
    defaultSlot: Option<String>,
    renderType: Option<String>,
    href: Option<String>,
    target: Option<String>,
    rel: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-breadcrumb-item {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "defaultSlot": defaultSlot.unwrap_or_default(),
            "renderType": renderType.unwrap_or_default(),
            "href": href.unwrap_or_default(),
            "target": target.unwrap_or_default(),
            "rel": rel.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-button-group`
#[component]
pub fn SlButtonGroup(
    defaultSlot: Option<String>,
    disableRole: Option<bool>,
    label: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-button-group {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "defaultSlot": defaultSlot.unwrap_or_default(),
            "disableRole": disableRole.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-card`
#[component]
pub fn SlCard(
    hasSlotController: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-card {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "hasSlotController": hasSlotController.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-carousel`
#[component]
pub fn SlCarousel(
    dependencies: Option<String>,
    r#loop: Option<bool>,
    navigation: Option<bool>,
    pagination: Option<bool>,
    autoplay: Option<bool>,
    autoplayInterval: Option<f64>,
    slidesPerPage: Option<f64>,
    slidesPerMove: Option<f64>,
    orientation: Option<String>,
    mouseDragging: Option<bool>,
    scrollContainer: Option<String>,
    paginationContainer: Option<String>,
    activeSlide: Option<f64>,
    scrolling: Option<bool>,
    dragging: Option<bool>,
    autoplayController: Option<String>,
    dragStartPosition: Option<String>,
    localize: Option<String>,
    mutationObserver: Option<String>,
    pendingSlideChange: Option<bool>,
    handleMouseDrag: Option<String>,
    handleMouseDragEnd: Option<String>,
    handleSlotChange: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-carousel {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "loop": r#loop.unwrap_or_default(),
            "navigation": navigation.unwrap_or_default(),
            "pagination": pagination.unwrap_or_default(),
            "autoplay": autoplay.unwrap_or_default(),
            "autoplayInterval": autoplayInterval.unwrap_or_default(),
            "slidesPerPage": slidesPerPage.unwrap_or_default(),
            "slidesPerMove": slidesPerMove.unwrap_or_default(),
            "orientation": orientation.unwrap_or_default(),
            "mouseDragging": mouseDragging.unwrap_or_default(),
            "scrollContainer": scrollContainer.unwrap_or_default(),
            "paginationContainer": paginationContainer.unwrap_or_default(),
            "activeSlide": activeSlide.unwrap_or_default(),
            "scrolling": scrolling.unwrap_or_default(),
            "dragging": dragging.unwrap_or_default(),
            "autoplayController": autoplayController.unwrap_or_default(),
            "dragStartPosition": dragStartPosition.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "mutationObserver": mutationObserver.unwrap_or_default(),
            "pendingSlideChange": pendingSlideChange.unwrap_or_default(),
            "handleMouseDrag": handleMouseDrag.unwrap_or_default(),
            "handleMouseDragEnd": handleMouseDragEnd.unwrap_or_default(),
            "handleSlotChange": handleSlotChange.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-carousel-item`
#[component]
pub fn SlCarouselItem(
    children: Element,
) -> Element {
    rsx! {
        sl-carousel-item {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-checkbox`
#[component]
pub fn SlCheckbox(
    dependencies: Option<String>,
    formControlController: Option<String>,
    hasSlotController: Option<String>,
    input: Option<String>,
    hasFocus: Option<bool>,
    title: Option<String>,
    name: Option<String>,
    value: Option<String>,
    size: Option<String>,
    disabled: Option<bool>,
    checked: Option<bool>,
    indeterminate: Option<bool>,
    defaultChecked: Option<bool>,
    form: Option<String>,
    required: Option<bool>,
    helpText: Option<String>,
    validity: Option<String>,
    validationMessage: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-checkbox {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "formControlController": formControlController.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "input": input.unwrap_or_default(),
            "hasFocus": hasFocus.unwrap_or_default(),
            "title": title.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "checked": checked.unwrap_or_default(),
            "indeterminate": indeterminate.unwrap_or_default(),
            "defaultChecked": defaultChecked.unwrap_or_default(),
            "form": form.unwrap_or_default(),
            "required": required.unwrap_or_default(),
            "helpText": helpText.unwrap_or_default(),
            "validity": validity.unwrap_or_default(),
            "validationMessage": validationMessage.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-color-picker`
#[component]
pub fn SlColorPicker(
    dependencies: Option<String>,
    formControlController: Option<String>,
    isSafeValue: Option<bool>,
    localize: Option<String>,
    base: Option<String>,
    input: Option<String>,
    dropdown: Option<String>,
    previewButton: Option<String>,
    trigger: Option<String>,
    hasFocus: Option<bool>,
    isDraggingGridHandle: Option<bool>,
    isEmpty: Option<bool>,
    inputValue: Option<String>,
    hue: Option<f64>,
    saturation: Option<f64>,
    brightness: Option<f64>,
    alpha: Option<f64>,
    value: Option<String>,
    defaultValue: Option<String>,
    label: Option<String>,
    format: Option<String>,
    inline: Option<bool>,
    size: Option<String>,
    noFormatToggle: Option<bool>,
    name: Option<String>,
    disabled: Option<bool>,
    hoist: Option<bool>,
    opacity: Option<bool>,
    uppercase: Option<bool>,
    swatches: Option<String>,
    form: Option<String>,
    required: Option<bool>,
    validity: Option<String>,
    validationMessage: Option<String>,
    handleFocusIn: Option<String>,
    handleFocusOut: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-color-picker {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "formControlController": formControlController.unwrap_or_default(),
            "isSafeValue": isSafeValue.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "base": base.unwrap_or_default(),
            "input": input.unwrap_or_default(),
            "dropdown": dropdown.unwrap_or_default(),
            "previewButton": previewButton.unwrap_or_default(),
            "trigger": trigger.unwrap_or_default(),
            "hasFocus": hasFocus.unwrap_or_default(),
            "isDraggingGridHandle": isDraggingGridHandle.unwrap_or_default(),
            "isEmpty": isEmpty.unwrap_or_default(),
            "inputValue": inputValue.unwrap_or_default(),
            "hue": hue.unwrap_or_default(),
            "saturation": saturation.unwrap_or_default(),
            "brightness": brightness.unwrap_or_default(),
            "alpha": alpha.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "defaultValue": defaultValue.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "format": format.unwrap_or_default(),
            "inline": inline.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "noFormatToggle": noFormatToggle.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "hoist": hoist.unwrap_or_default(),
            "opacity": opacity.unwrap_or_default(),
            "uppercase": uppercase.unwrap_or_default(),
            "swatches": swatches.unwrap_or_default(),
            "form": form.unwrap_or_default(),
            "required": required.unwrap_or_default(),
            "validity": validity.unwrap_or_default(),
            "validationMessage": validationMessage.unwrap_or_default(),
            "handleFocusIn": handleFocusIn.unwrap_or_default(),
            "handleFocusOut": handleFocusOut.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-copy-button`
#[component]
pub fn SlCopyButton(
    dependencies: Option<String>,
    localize: Option<String>,
    copyIcon: Option<String>,
    successIcon: Option<String>,
    errorIcon: Option<String>,
    tooltip: Option<String>,
    isCopying: Option<bool>,
    status: Option<String>,
    value: Option<String>,
    from: Option<String>,
    disabled: Option<bool>,
    copyLabel: Option<String>,
    successLabel: Option<String>,
    errorLabel: Option<String>,
    feedbackDuration: Option<f64>,
    tooltipPlacement: Option<String>,
    hoist: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-copy-button {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "copyIcon": copyIcon.unwrap_or_default(),
            "successIcon": successIcon.unwrap_or_default(),
            "errorIcon": errorIcon.unwrap_or_default(),
            "tooltip": tooltip.unwrap_or_default(),
            "isCopying": isCopying.unwrap_or_default(),
            "status": status.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "from": from.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "copyLabel": copyLabel.unwrap_or_default(),
            "successLabel": successLabel.unwrap_or_default(),
            "errorLabel": errorLabel.unwrap_or_default(),
            "feedbackDuration": feedbackDuration.unwrap_or_default(),
            "tooltipPlacement": tooltipPlacement.unwrap_or_default(),
            "hoist": hoist.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-details`
#[component]
pub fn SlDetails(
    dependencies: Option<String>,
    localize: Option<String>,
    details: Option<String>,
    header: Option<String>,
    body: Option<String>,
    expandIconSlot: Option<String>,
    detailsObserver: Option<String>,
    open: Option<bool>,
    summary: Option<String>,
    disabled: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-details {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "details": details.unwrap_or_default(),
            "header": header.unwrap_or_default(),
            "body": body.unwrap_or_default(),
            "expandIconSlot": expandIconSlot.unwrap_or_default(),
            "detailsObserver": detailsObserver.unwrap_or_default(),
            "open": open.unwrap_or_default(),
            "summary": summary.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-dialog`
#[component]
pub fn SlDialog(
    dependencies: Option<String>,
    hasSlotController: Option<String>,
    localize: Option<String>,
    originalTrigger: Option<String>,
    modal: Option<String>,
    closeWatcher: Option<String>,
    dialog: Option<String>,
    panel: Option<String>,
    overlay: Option<String>,
    open: Option<bool>,
    label: Option<String>,
    noHeader: Option<bool>,
    handleDocumentKeyDown: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-dialog {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "originalTrigger": originalTrigger.unwrap_or_default(),
            "modal": modal.unwrap_or_default(),
            "closeWatcher": closeWatcher.unwrap_or_default(),
            "dialog": dialog.unwrap_or_default(),
            "panel": panel.unwrap_or_default(),
            "overlay": overlay.unwrap_or_default(),
            "open": open.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "noHeader": noHeader.unwrap_or_default(),
            "handleDocumentKeyDown": handleDocumentKeyDown.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-divider`
#[component]
pub fn SlDivider(
    vertical: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-divider {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "vertical": vertical.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-drawer`
#[component]
pub fn SlDrawer(
    dependencies: Option<String>,
    hasSlotController: Option<String>,
    localize: Option<String>,
    originalTrigger: Option<String>,
    modal: Option<String>,
    closeWatcher: Option<String>,
    drawer: Option<String>,
    panel: Option<String>,
    overlay: Option<String>,
    open: Option<bool>,
    label: Option<String>,
    placement: Option<String>,
    contained: Option<bool>,
    noHeader: Option<bool>,
    handleDocumentKeyDown: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-drawer {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "originalTrigger": originalTrigger.unwrap_or_default(),
            "modal": modal.unwrap_or_default(),
            "closeWatcher": closeWatcher.unwrap_or_default(),
            "drawer": drawer.unwrap_or_default(),
            "panel": panel.unwrap_or_default(),
            "overlay": overlay.unwrap_or_default(),
            "open": open.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "placement": placement.unwrap_or_default(),
            "contained": contained.unwrap_or_default(),
            "noHeader": noHeader.unwrap_or_default(),
            "handleDocumentKeyDown": handleDocumentKeyDown.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-dropdown`
#[component]
pub fn SlDropdown(
    dependencies: Option<String>,
    popup: Option<String>,
    trigger: Option<String>,
    panel: Option<String>,
    localize: Option<String>,
    closeWatcher: Option<String>,
    open: Option<bool>,
    placement: Option<String>,
    disabled: Option<bool>,
    stayOpenOnSelect: Option<bool>,
    containingElement: Option<String>,
    distance: Option<f64>,
    skidding: Option<f64>,
    hoist: Option<bool>,
    sync: Option<String>,
    handleKeyDown: Option<String>,
    handleDocumentKeyDown: Option<String>,
    handleDocumentMouseDown: Option<String>,
    handlePanelSelect: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-dropdown {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "popup": popup.unwrap_or_default(),
            "trigger": trigger.unwrap_or_default(),
            "panel": panel.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "closeWatcher": closeWatcher.unwrap_or_default(),
            "open": open.unwrap_or_default(),
            "placement": placement.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "stayOpenOnSelect": stayOpenOnSelect.unwrap_or_default(),
            "containingElement": containingElement.unwrap_or_default(),
            "distance": distance.unwrap_or_default(),
            "skidding": skidding.unwrap_or_default(),
            "hoist": hoist.unwrap_or_default(),
            "sync": sync.unwrap_or_default(),
            "handleKeyDown": handleKeyDown.unwrap_or_default(),
            "handleDocumentKeyDown": handleDocumentKeyDown.unwrap_or_default(),
            "handleDocumentMouseDown": handleDocumentMouseDown.unwrap_or_default(),
            "handlePanelSelect": handlePanelSelect.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-format-bytes`
#[component]
pub fn SlFormatBytes(
    localize: Option<String>,
    value: Option<f64>,
    unit: Option<String>,
    display: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-format-bytes {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "localize": localize.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "unit": unit.unwrap_or_default(),
            "display": display.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-format-date`
#[component]
pub fn SlFormatDate(
    localize: Option<String>,
    date: Option<String>,
    weekday: Option<String>,
    era: Option<String>,
    year: Option<String>,
    month: Option<String>,
    day: Option<String>,
    hour: Option<String>,
    minute: Option<String>,
    second: Option<String>,
    timeZoneName: Option<String>,
    timeZone: Option<String>,
    hourFormat: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-format-date {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "localize": localize.unwrap_or_default(),
            "date": date.unwrap_or_default(),
            "weekday": weekday.unwrap_or_default(),
            "era": era.unwrap_or_default(),
            "year": year.unwrap_or_default(),
            "month": month.unwrap_or_default(),
            "day": day.unwrap_or_default(),
            "hour": hour.unwrap_or_default(),
            "minute": minute.unwrap_or_default(),
            "second": second.unwrap_or_default(),
            "timeZoneName": timeZoneName.unwrap_or_default(),
            "timeZone": timeZone.unwrap_or_default(),
            "hourFormat": hourFormat.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-format-number`
#[component]
pub fn SlFormatNumber(
    localize: Option<String>,
    value: Option<f64>,
    r#type: Option<String>,
    noGrouping: Option<bool>,
    currency: Option<String>,
    currencyDisplay: Option<String>,
    minimumIntegerDigits: Option<f64>,
    minimumFractionDigits: Option<f64>,
    maximumFractionDigits: Option<f64>,
    minimumSignificantDigits: Option<f64>,
    maximumSignificantDigits: Option<f64>,
    children: Element,
) -> Element {
    rsx! {
        sl-format-number {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "localize": localize.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "type": r#type.unwrap_or_default(),
            "noGrouping": noGrouping.unwrap_or_default(),
            "currency": currency.unwrap_or_default(),
            "currencyDisplay": currencyDisplay.unwrap_or_default(),
            "minimumIntegerDigits": minimumIntegerDigits.unwrap_or_default(),
            "minimumFractionDigits": minimumFractionDigits.unwrap_or_default(),
            "maximumFractionDigits": maximumFractionDigits.unwrap_or_default(),
            "minimumSignificantDigits": minimumSignificantDigits.unwrap_or_default(),
            "maximumSignificantDigits": maximumSignificantDigits.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-icon`
#[component]
pub fn SlIcon(
    initialRender: Option<bool>,
    svg: Option<String>,
    name: Option<String>,
    src: Option<String>,
    label: Option<String>,
    library: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-icon {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "initialRender": initialRender.unwrap_or_default(),
            "svg": svg.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "src": src.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "library": library.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-include`
#[component]
pub fn SlInclude(
    src: Option<String>,
    mode: Option<String>,
    allowScripts: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-include {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "src": src.unwrap_or_default(),
            "mode": mode.unwrap_or_default(),
            "allowScripts": allowScripts.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-icon-button`
#[component]
pub fn SlIconButton(
    dependencies: Option<String>,
    button: Option<String>,
    hasFocus: Option<bool>,
    name: Option<String>,
    library: Option<String>,
    src: Option<String>,
    href: Option<String>,
    target: Option<String>,
    download: Option<String>,
    label: Option<String>,
    disabled: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-icon-button {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "button": button.unwrap_or_default(),
            "hasFocus": hasFocus.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "library": library.unwrap_or_default(),
            "src": src.unwrap_or_default(),
            "href": href.unwrap_or_default(),
            "target": target.unwrap_or_default(),
            "download": download.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-image-comparer`
#[component]
pub fn SlImageComparer(
    scopedElement: Option<String>,
    localize: Option<String>,
    base: Option<String>,
    handle: Option<String>,
    position: Option<f64>,
    children: Element,
) -> Element {
    rsx! {
        sl-image-comparer {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "scopedElement": scopedElement.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "base": base.unwrap_or_default(),
            "handle": handle.unwrap_or_default(),
            "position": position.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-input`
#[component]
pub fn SlInput(
    dependencies: Option<String>,
    formControlController: Option<String>,
    hasSlotController: Option<String>,
    localize: Option<String>,
    input: Option<String>,
    hasFocus: Option<bool>,
    title: Option<String>,
    r#type: Option<String>,
    name: Option<String>,
    value: Option<String>,
    defaultValue: Option<String>,
    size: Option<String>,
    filled: Option<bool>,
    pill: Option<bool>,
    label: Option<String>,
    helpText: Option<String>,
    clearable: Option<bool>,
    disabled: Option<bool>,
    placeholder: Option<String>,
    readonly: Option<bool>,
    passwordToggle: Option<bool>,
    passwordVisible: Option<bool>,
    noSpinButtons: Option<bool>,
    form: Option<String>,
    required: Option<bool>,
    pattern: Option<String>,
    minlength: Option<f64>,
    maxlength: Option<f64>,
    min: Option<String>,
    max: Option<String>,
    step: Option<String>,
    autocapitalize: Option<String>,
    autocorrect: Option<String>,
    autocomplete: Option<String>,
    autofocus: Option<bool>,
    enterkeyhint: Option<String>,
    spellcheck: Option<bool>,
    inputmode: Option<String>,
    valueAsDate: Option<String>,
    valueAsNumber: Option<String>,
    validity: Option<String>,
    validationMessage: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-input {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "formControlController": formControlController.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "input": input.unwrap_or_default(),
            "hasFocus": hasFocus.unwrap_or_default(),
            "title": title.unwrap_or_default(),
            "type": r#type.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "defaultValue": defaultValue.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "filled": filled.unwrap_or_default(),
            "pill": pill.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "helpText": helpText.unwrap_or_default(),
            "clearable": clearable.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "placeholder": placeholder.unwrap_or_default(),
            "readonly": readonly.unwrap_or_default(),
            "passwordToggle": passwordToggle.unwrap_or_default(),
            "passwordVisible": passwordVisible.unwrap_or_default(),
            "noSpinButtons": noSpinButtons.unwrap_or_default(),
            "form": form.unwrap_or_default(),
            "required": required.unwrap_or_default(),
            "pattern": pattern.unwrap_or_default(),
            "minlength": minlength.unwrap_or_default(),
            "maxlength": maxlength.unwrap_or_default(),
            "min": min.unwrap_or_default(),
            "max": max.unwrap_or_default(),
            "step": step.unwrap_or_default(),
            "autocapitalize": autocapitalize.unwrap_or_default(),
            "autocorrect": autocorrect.unwrap_or_default(),
            "autocomplete": autocomplete.unwrap_or_default(),
            "autofocus": autofocus.unwrap_or_default(),
            "enterkeyhint": enterkeyhint.unwrap_or_default(),
            "spellcheck": spellcheck.unwrap_or_default(),
            "inputmode": inputmode.unwrap_or_default(),
            "valueAsDate": valueAsDate.unwrap_or_default(),
            "valueAsNumber": valueAsNumber.unwrap_or_default(),
            "validity": validity.unwrap_or_default(),
            "validationMessage": validationMessage.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-menu`
#[component]
pub fn SlMenu(
    defaultSlot: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-menu {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "defaultSlot": defaultSlot.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-menu-label`
#[component]
pub fn SlMenuLabel(
    children: Element,
) -> Element {
    rsx! {
        sl-menu-label {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-mutation-observer`
#[component]
pub fn SlMutationObserver(
    mutationObserver: Option<String>,
    attr: Option<String>,
    attrOldValue: Option<bool>,
    charData: Option<bool>,
    charDataOldValue: Option<bool>,
    childList: Option<bool>,
    disabled: Option<bool>,
    handleMutation: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-mutation-observer {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "mutationObserver": mutationObserver.unwrap_or_default(),
            "attr": attr.unwrap_or_default(),
            "attrOldValue": attrOldValue.unwrap_or_default(),
            "charData": charData.unwrap_or_default(),
            "charDataOldValue": charDataOldValue.unwrap_or_default(),
            "childList": childList.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "handleMutation": handleMutation.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-menu-item`
#[component]
pub fn SlMenuItem(
    dependencies: Option<String>,
    cachedTextLabel: Option<String>,
    localize: Option<String>,
    defaultSlot: Option<String>,
    menuItem: Option<String>,
    r#type: Option<String>,
    checked: Option<bool>,
    value: Option<String>,
    loading: Option<bool>,
    disabled: Option<bool>,
    hasSlotController: Option<String>,
    submenuController: Option<String>,
    handleHostClick: Option<String>,
    handleMouseOver: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-menu-item {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "cachedTextLabel": cachedTextLabel.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "defaultSlot": defaultSlot.unwrap_or_default(),
            "menuItem": menuItem.unwrap_or_default(),
            "type": r#type.unwrap_or_default(),
            "checked": checked.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "loading": loading.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "submenuController": submenuController.unwrap_or_default(),
            "handleHostClick": handleHostClick.unwrap_or_default(),
            "handleMouseOver": handleMouseOver.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-option`
#[component]
pub fn SlOption(
    dependencies: Option<String>,
    localize: Option<String>,
    isInitialized: Option<bool>,
    defaultSlot: Option<String>,
    current: Option<bool>,
    selected: Option<bool>,
    hasHover: Option<bool>,
    value: Option<String>,
    disabled: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-option {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "isInitialized": isInitialized.unwrap_or_default(),
            "defaultSlot": defaultSlot.unwrap_or_default(),
            "current": current.unwrap_or_default(),
            "selected": selected.unwrap_or_default(),
            "hasHover": hasHover.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-popup`
#[component]
pub fn SlPopup(
    anchorEl: Option<String>,
    cleanup: Option<String>,
    localize: Option<String>,
    popup: Option<String>,
    arrowEl: Option<String>,
    anchor: Option<String>,
    active: Option<bool>,
    placement: Option<String>,
    strategy: Option<String>,
    distance: Option<f64>,
    skidding: Option<f64>,
    arrow: Option<bool>,
    arrowPlacement: Option<String>,
    arrowPadding: Option<f64>,
    flip: Option<bool>,
    flipFallbackPlacements: Option<String>,
    flipFallbackStrategy: Option<String>,
    flipBoundary: Option<String>,
    flipPadding: Option<f64>,
    shift: Option<bool>,
    shiftBoundary: Option<String>,
    shiftPadding: Option<f64>,
    autoSize: Option<String>,
    sync: Option<String>,
    autoSizeBoundary: Option<String>,
    autoSizePadding: Option<f64>,
    hoverBridge: Option<bool>,
    updateHoverBridge: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-popup {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "anchorEl": anchorEl.unwrap_or_default(),
            "cleanup": cleanup.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "popup": popup.unwrap_or_default(),
            "arrowEl": arrowEl.unwrap_or_default(),
            "anchor": anchor.unwrap_or_default(),
            "active": active.unwrap_or_default(),
            "placement": placement.unwrap_or_default(),
            "strategy": strategy.unwrap_or_default(),
            "distance": distance.unwrap_or_default(),
            "skidding": skidding.unwrap_or_default(),
            "arrow": arrow.unwrap_or_default(),
            "arrowPlacement": arrowPlacement.unwrap_or_default(),
            "arrowPadding": arrowPadding.unwrap_or_default(),
            "flip": flip.unwrap_or_default(),
            "flipFallbackPlacements": flipFallbackPlacements.unwrap_or_default(),
            "flipFallbackStrategy": flipFallbackStrategy.unwrap_or_default(),
            "flipBoundary": flipBoundary.unwrap_or_default(),
            "flipPadding": flipPadding.unwrap_or_default(),
            "shift": shift.unwrap_or_default(),
            "shiftBoundary": shiftBoundary.unwrap_or_default(),
            "shiftPadding": shiftPadding.unwrap_or_default(),
            "autoSize": autoSize.unwrap_or_default(),
            "sync": sync.unwrap_or_default(),
            "autoSizeBoundary": autoSizeBoundary.unwrap_or_default(),
            "autoSizePadding": autoSizePadding.unwrap_or_default(),
            "hoverBridge": hoverBridge.unwrap_or_default(),
            "updateHoverBridge": updateHoverBridge.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-progress-bar`
#[component]
pub fn SlProgressBar(
    localize: Option<String>,
    value: Option<f64>,
    indeterminate: Option<bool>,
    label: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-progress-bar {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "localize": localize.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "indeterminate": indeterminate.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-progress-ring`
#[component]
pub fn SlProgressRing(
    localize: Option<String>,
    indicator: Option<String>,
    indicatorOffset: Option<String>,
    value: Option<f64>,
    label: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-progress-ring {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "localize": localize.unwrap_or_default(),
            "indicator": indicator.unwrap_or_default(),
            "indicatorOffset": indicatorOffset.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-radio`
#[component]
pub fn SlRadio(
    dependencies: Option<String>,
    checked: Option<bool>,
    hasFocus: Option<bool>,
    value: Option<String>,
    size: Option<String>,
    disabled: Option<bool>,
    handleBlur: Option<String>,
    handleClick: Option<String>,
    handleFocus: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-radio {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "checked": checked.unwrap_or_default(),
            "hasFocus": hasFocus.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "handleBlur": handleBlur.unwrap_or_default(),
            "handleClick": handleClick.unwrap_or_default(),
            "handleFocus": handleFocus.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-qr-code`
#[component]
pub fn SlQrCode(
    canvas: Option<String>,
    value: Option<String>,
    label: Option<String>,
    size: Option<f64>,
    fill: Option<String>,
    background: Option<String>,
    radius: Option<f64>,
    errorCorrection: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-qr-code {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "canvas": canvas.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "fill": fill.unwrap_or_default(),
            "background": background.unwrap_or_default(),
            "radius": radius.unwrap_or_default(),
            "errorCorrection": errorCorrection.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-radio-button`
#[component]
pub fn SlRadioButton(
    hasSlotController: Option<String>,
    input: Option<String>,
    hiddenInput: Option<String>,
    hasFocus: Option<bool>,
    value: Option<String>,
    disabled: Option<bool>,
    size: Option<String>,
    pill: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-radio-button {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "input": input.unwrap_or_default(),
            "hiddenInput": hiddenInput.unwrap_or_default(),
            "hasFocus": hasFocus.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "pill": pill.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-radio-group`
#[component]
pub fn SlRadioGroup(
    dependencies: Option<String>,
    formControlController: Option<String>,
    hasSlotController: Option<String>,
    customValidityMessage: Option<String>,
    validationTimeout: Option<f64>,
    defaultSlot: Option<String>,
    validationInput: Option<String>,
    hasButtonGroup: Option<bool>,
    errorMessage: Option<String>,
    defaultValue: Option<String>,
    label: Option<String>,
    helpText: Option<String>,
    name: Option<String>,
    value: Option<String>,
    size: Option<String>,
    form: Option<String>,
    required: Option<bool>,
    validity: Option<String>,
    validationMessage: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-radio-group {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "formControlController": formControlController.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "customValidityMessage": customValidityMessage.unwrap_or_default(),
            "validationTimeout": validationTimeout.unwrap_or_default(),
            "defaultSlot": defaultSlot.unwrap_or_default(),
            "validationInput": validationInput.unwrap_or_default(),
            "hasButtonGroup": hasButtonGroup.unwrap_or_default(),
            "errorMessage": errorMessage.unwrap_or_default(),
            "defaultValue": defaultValue.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "helpText": helpText.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "form": form.unwrap_or_default(),
            "required": required.unwrap_or_default(),
            "validity": validity.unwrap_or_default(),
            "validationMessage": validationMessage.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-range`
#[component]
pub fn SlRange(
    formControlController: Option<String>,
    hasSlotController: Option<String>,
    localize: Option<String>,
    resizeObserver: Option<String>,
    input: Option<String>,
    output: Option<String>,
    hasFocus: Option<bool>,
    hasTooltip: Option<bool>,
    title: Option<String>,
    name: Option<String>,
    value: Option<f64>,
    label: Option<String>,
    helpText: Option<String>,
    disabled: Option<bool>,
    min: Option<f64>,
    max: Option<f64>,
    step: Option<f64>,
    tooltip: Option<String>,
    tooltipFormatter: Option<String>,
    form: Option<String>,
    defaultValue: Option<f64>,
    validity: Option<String>,
    validationMessage: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-range {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "formControlController": formControlController.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "resizeObserver": resizeObserver.unwrap_or_default(),
            "input": input.unwrap_or_default(),
            "output": output.unwrap_or_default(),
            "hasFocus": hasFocus.unwrap_or_default(),
            "hasTooltip": hasTooltip.unwrap_or_default(),
            "title": title.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "helpText": helpText.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "min": min.unwrap_or_default(),
            "max": max.unwrap_or_default(),
            "step": step.unwrap_or_default(),
            "tooltip": tooltip.unwrap_or_default(),
            "tooltipFormatter": tooltipFormatter.unwrap_or_default(),
            "form": form.unwrap_or_default(),
            "defaultValue": defaultValue.unwrap_or_default(),
            "validity": validity.unwrap_or_default(),
            "validationMessage": validationMessage.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-rating`
#[component]
pub fn SlRating(
    dependencies: Option<String>,
    localize: Option<String>,
    rating: Option<String>,
    hoverValue: Option<f64>,
    isHovering: Option<bool>,
    label: Option<String>,
    value: Option<f64>,
    max: Option<f64>,
    precision: Option<f64>,
    readonly: Option<bool>,
    disabled: Option<bool>,
    getSymbol: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-rating {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "rating": rating.unwrap_or_default(),
            "hoverValue": hoverValue.unwrap_or_default(),
            "isHovering": isHovering.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "max": max.unwrap_or_default(),
            "precision": precision.unwrap_or_default(),
            "readonly": readonly.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "getSymbol": getSymbol.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-relative-time`
#[component]
pub fn SlRelativeTime(
    localize: Option<String>,
    updateTimeout: Option<f64>,
    isoTime: Option<String>,
    relativeTime: Option<String>,
    date: Option<String>,
    format: Option<String>,
    numeric: Option<String>,
    sync: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-relative-time {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "localize": localize.unwrap_or_default(),
            "updateTimeout": updateTimeout.unwrap_or_default(),
            "isoTime": isoTime.unwrap_or_default(),
            "relativeTime": relativeTime.unwrap_or_default(),
            "date": date.unwrap_or_default(),
            "format": format.unwrap_or_default(),
            "numeric": numeric.unwrap_or_default(),
            "sync": sync.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-resize-observer`
#[component]
pub fn SlResizeObserver(
    resizeObserver: Option<String>,
    observedElements: Option<String>,
    disabled: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-resize-observer {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "resizeObserver": resizeObserver.unwrap_or_default(),
            "observedElements": observedElements.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-skeleton`
#[component]
pub fn SlSkeleton(
    effect: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-skeleton {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "effect": effect.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-select`
#[component]
pub fn SlSelect(
    dependencies: Option<String>,
    formControlController: Option<String>,
    hasSlotController: Option<String>,
    localize: Option<String>,
    typeToSelectString: Option<String>,
    typeToSelectTimeout: Option<f64>,
    closeWatcher: Option<String>,
    popup: Option<String>,
    combobox: Option<String>,
    displayInput: Option<String>,
    valueInput: Option<String>,
    listbox: Option<String>,
    hasFocus: Option<bool>,
    displayLabel: Option<String>,
    currentOption: Option<String>,
    selectedOptions: Option<String>,
    valueHasChanged: Option<bool>,
    name: Option<String>,
    value: Option<String>,
    defaultValue: Option<String>,
    size: Option<String>,
    placeholder: Option<String>,
    multiple: Option<bool>,
    maxOptionsVisible: Option<f64>,
    disabled: Option<bool>,
    clearable: Option<bool>,
    open: Option<bool>,
    hoist: Option<bool>,
    filled: Option<bool>,
    pill: Option<bool>,
    label: Option<String>,
    placement: Option<String>,
    helpText: Option<String>,
    form: Option<String>,
    required: Option<bool>,
    getTag: Option<String>,
    validity: Option<String>,
    validationMessage: Option<String>,
    handleDocumentFocusIn: Option<String>,
    handleDocumentKeyDown: Option<String>,
    handleDocumentMouseDown: Option<String>,
    tags: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-select {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "formControlController": formControlController.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "typeToSelectString": typeToSelectString.unwrap_or_default(),
            "typeToSelectTimeout": typeToSelectTimeout.unwrap_or_default(),
            "closeWatcher": closeWatcher.unwrap_or_default(),
            "popup": popup.unwrap_or_default(),
            "combobox": combobox.unwrap_or_default(),
            "displayInput": displayInput.unwrap_or_default(),
            "valueInput": valueInput.unwrap_or_default(),
            "listbox": listbox.unwrap_or_default(),
            "hasFocus": hasFocus.unwrap_or_default(),
            "displayLabel": displayLabel.unwrap_or_default(),
            "currentOption": currentOption.unwrap_or_default(),
            "selectedOptions": selectedOptions.unwrap_or_default(),
            "valueHasChanged": valueHasChanged.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "defaultValue": defaultValue.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "placeholder": placeholder.unwrap_or_default(),
            "multiple": multiple.unwrap_or_default(),
            "maxOptionsVisible": maxOptionsVisible.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "clearable": clearable.unwrap_or_default(),
            "open": open.unwrap_or_default(),
            "hoist": hoist.unwrap_or_default(),
            "filled": filled.unwrap_or_default(),
            "pill": pill.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "placement": placement.unwrap_or_default(),
            "helpText": helpText.unwrap_or_default(),
            "form": form.unwrap_or_default(),
            "required": required.unwrap_or_default(),
            "getTag": getTag.unwrap_or_default(),
            "validity": validity.unwrap_or_default(),
            "validationMessage": validationMessage.unwrap_or_default(),
            "handleDocumentFocusIn": handleDocumentFocusIn.unwrap_or_default(),
            "handleDocumentKeyDown": handleDocumentKeyDown.unwrap_or_default(),
            "handleDocumentMouseDown": handleDocumentMouseDown.unwrap_or_default(),
            "tags": tags.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-spinner`
#[component]
pub fn SlSpinner(
    localize: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-spinner {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "localize": localize.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-switch`
#[component]
pub fn SlSwitch(
    formControlController: Option<String>,
    hasSlotController: Option<String>,
    input: Option<String>,
    hasFocus: Option<bool>,
    title: Option<String>,
    name: Option<String>,
    value: Option<String>,
    size: Option<String>,
    disabled: Option<bool>,
    checked: Option<bool>,
    defaultChecked: Option<bool>,
    form: Option<String>,
    required: Option<bool>,
    helpText: Option<String>,
    validity: Option<String>,
    validationMessage: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-switch {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "formControlController": formControlController.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "input": input.unwrap_or_default(),
            "hasFocus": hasFocus.unwrap_or_default(),
            "title": title.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "checked": checked.unwrap_or_default(),
            "defaultChecked": defaultChecked.unwrap_or_default(),
            "form": form.unwrap_or_default(),
            "required": required.unwrap_or_default(),
            "helpText": helpText.unwrap_or_default(),
            "validity": validity.unwrap_or_default(),
            "validationMessage": validationMessage.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-split-panel`
#[component]
pub fn SlSplitPanel(
    cachedPositionInPixels: Option<f64>,
    isCollapsed: Option<bool>,
    localize: Option<String>,
    positionBeforeCollapsing: Option<f64>,
    resizeObserver: Option<String>,
    size: Option<f64>,
    divider: Option<String>,
    position: Option<f64>,
    positionInPixels: Option<f64>,
    vertical: Option<bool>,
    disabled: Option<bool>,
    primary: Option<String>,
    snapValue: Option<String>,
    snapFunction: Option<String>,
    snap: Option<String>,
    snapThreshold: Option<f64>,
    children: Element,
) -> Element {
    rsx! {
        sl-split-panel {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "cachedPositionInPixels": cachedPositionInPixels.unwrap_or_default(),
            "isCollapsed": isCollapsed.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "positionBeforeCollapsing": positionBeforeCollapsing.unwrap_or_default(),
            "resizeObserver": resizeObserver.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "divider": divider.unwrap_or_default(),
            "position": position.unwrap_or_default(),
            "positionInPixels": positionInPixels.unwrap_or_default(),
            "vertical": vertical.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "primary": primary.unwrap_or_default(),
            "snapValue": snapValue.unwrap_or_default(),
            "snapFunction": snapFunction.unwrap_or_default(),
            "snap": snap.unwrap_or_default(),
            "snapThreshold": snapThreshold.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-tab-group`
#[component]
pub fn SlTabGroup(
    dependencies: Option<String>,
    activeTab: Option<String>,
    mutationObserver: Option<String>,
    resizeObserver: Option<String>,
    tabs: Option<String>,
    focusableTabs: Option<String>,
    panels: Option<String>,
    localize: Option<String>,
    tabGroup: Option<String>,
    body: Option<String>,
    nav: Option<String>,
    indicator: Option<String>,
    hasScrollControls: Option<bool>,
    shouldHideScrollStartButton: Option<bool>,
    shouldHideScrollEndButton: Option<bool>,
    placement: Option<String>,
    activation: Option<String>,
    noScrollControls: Option<bool>,
    fixedScrollControls: Option<bool>,
    scrollOffset: Option<f64>,
    children: Element,
) -> Element {
    rsx! {
        sl-tab-group {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "activeTab": activeTab.unwrap_or_default(),
            "mutationObserver": mutationObserver.unwrap_or_default(),
            "resizeObserver": resizeObserver.unwrap_or_default(),
            "tabs": tabs.unwrap_or_default(),
            "focusableTabs": focusableTabs.unwrap_or_default(),
            "panels": panels.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "tabGroup": tabGroup.unwrap_or_default(),
            "body": body.unwrap_or_default(),
            "nav": nav.unwrap_or_default(),
            "indicator": indicator.unwrap_or_default(),
            "hasScrollControls": hasScrollControls.unwrap_or_default(),
            "shouldHideScrollStartButton": shouldHideScrollStartButton.unwrap_or_default(),
            "shouldHideScrollEndButton": shouldHideScrollEndButton.unwrap_or_default(),
            "placement": placement.unwrap_or_default(),
            "activation": activation.unwrap_or_default(),
            "noScrollControls": noScrollControls.unwrap_or_default(),
            "fixedScrollControls": fixedScrollControls.unwrap_or_default(),
            "scrollOffset": scrollOffset.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-tab`
#[component]
pub fn SlTab(
    dependencies: Option<String>,
    localize: Option<String>,
    attrId: Option<f64>,
    componentId: Option<String>,
    tab: Option<String>,
    panel: Option<String>,
    active: Option<bool>,
    closable: Option<bool>,
    disabled: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-tab {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "attrId": attrId.unwrap_or_default(),
            "componentId": componentId.unwrap_or_default(),
            "tab": tab.unwrap_or_default(),
            "panel": panel.unwrap_or_default(),
            "active": active.unwrap_or_default(),
            "closable": closable.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-tab-panel`
#[component]
pub fn SlTabPanel(
    attrId: Option<f64>,
    componentId: Option<String>,
    name: Option<String>,
    active: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-tab-panel {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "attrId": attrId.unwrap_or_default(),
            "componentId": componentId.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "active": active.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-textarea`
#[component]
pub fn SlTextarea(
    formControlController: Option<String>,
    hasSlotController: Option<String>,
    resizeObserver: Option<String>,
    input: Option<String>,
    sizeAdjuster: Option<String>,
    hasFocus: Option<bool>,
    title: Option<String>,
    name: Option<String>,
    value: Option<String>,
    size: Option<String>,
    filled: Option<bool>,
    label: Option<String>,
    helpText: Option<String>,
    placeholder: Option<String>,
    rows: Option<f64>,
    resize: Option<String>,
    disabled: Option<bool>,
    readonly: Option<bool>,
    form: Option<String>,
    required: Option<bool>,
    minlength: Option<f64>,
    maxlength: Option<f64>,
    autocapitalize: Option<String>,
    autocorrect: Option<String>,
    autocomplete: Option<String>,
    autofocus: Option<bool>,
    enterkeyhint: Option<String>,
    spellcheck: Option<bool>,
    inputmode: Option<String>,
    defaultValue: Option<String>,
    validity: Option<String>,
    validationMessage: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-textarea {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "formControlController": formControlController.unwrap_or_default(),
            "hasSlotController": hasSlotController.unwrap_or_default(),
            "resizeObserver": resizeObserver.unwrap_or_default(),
            "input": input.unwrap_or_default(),
            "sizeAdjuster": sizeAdjuster.unwrap_or_default(),
            "hasFocus": hasFocus.unwrap_or_default(),
            "title": title.unwrap_or_default(),
            "name": name.unwrap_or_default(),
            "value": value.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "filled": filled.unwrap_or_default(),
            "label": label.unwrap_or_default(),
            "helpText": helpText.unwrap_or_default(),
            "placeholder": placeholder.unwrap_or_default(),
            "rows": rows.unwrap_or_default(),
            "resize": resize.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "readonly": readonly.unwrap_or_default(),
            "form": form.unwrap_or_default(),
            "required": required.unwrap_or_default(),
            "minlength": minlength.unwrap_or_default(),
            "maxlength": maxlength.unwrap_or_default(),
            "autocapitalize": autocapitalize.unwrap_or_default(),
            "autocorrect": autocorrect.unwrap_or_default(),
            "autocomplete": autocomplete.unwrap_or_default(),
            "autofocus": autofocus.unwrap_or_default(),
            "enterkeyhint": enterkeyhint.unwrap_or_default(),
            "spellcheck": spellcheck.unwrap_or_default(),
            "inputmode": inputmode.unwrap_or_default(),
            "defaultValue": defaultValue.unwrap_or_default(),
            "validity": validity.unwrap_or_default(),
            "validationMessage": validationMessage.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-tag`
#[component]
pub fn SlTag(
    dependencies: Option<String>,
    localize: Option<String>,
    variant: Option<String>,
    size: Option<String>,
    pill: Option<bool>,
    removable: Option<bool>,
    children: Element,
) -> Element {
    rsx! {
        sl-tag {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "variant": variant.unwrap_or_default(),
            "size": size.unwrap_or_default(),
            "pill": pill.unwrap_or_default(),
            "removable": removable.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-tooltip`
#[component]
pub fn SlTooltip(
    dependencies: Option<String>,
    hoverTimeout: Option<f64>,
    localize: Option<String>,
    closeWatcher: Option<String>,
    defaultSlot: Option<String>,
    body: Option<String>,
    popup: Option<String>,
    content: Option<String>,
    placement: Option<String>,
    disabled: Option<bool>,
    distance: Option<f64>,
    open: Option<bool>,
    skidding: Option<f64>,
    trigger: Option<String>,
    hoist: Option<bool>,
    handleBlur: Option<String>,
    handleClick: Option<String>,
    handleFocus: Option<String>,
    handleDocumentKeyDown: Option<String>,
    handleMouseOver: Option<String>,
    handleMouseOut: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-tooltip {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "hoverTimeout": hoverTimeout.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "closeWatcher": closeWatcher.unwrap_or_default(),
            "defaultSlot": defaultSlot.unwrap_or_default(),
            "body": body.unwrap_or_default(),
            "popup": popup.unwrap_or_default(),
            "content": content.unwrap_or_default(),
            "placement": placement.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "distance": distance.unwrap_or_default(),
            "open": open.unwrap_or_default(),
            "skidding": skidding.unwrap_or_default(),
            "trigger": trigger.unwrap_or_default(),
            "hoist": hoist.unwrap_or_default(),
            "handleBlur": handleBlur.unwrap_or_default(),
            "handleClick": handleClick.unwrap_or_default(),
            "handleFocus": handleFocus.unwrap_or_default(),
            "handleDocumentKeyDown": handleDocumentKeyDown.unwrap_or_default(),
            "handleMouseOver": handleMouseOver.unwrap_or_default(),
            "handleMouseOut": handleMouseOut.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-tree`
#[component]
pub fn SlTree(
    defaultSlot: Option<String>,
    expandedIconSlot: Option<String>,
    collapsedIconSlot: Option<String>,
    selection: Option<String>,
    lastFocusedItem: Option<String>,
    mutationObserver: Option<String>,
    clickTarget: Option<String>,
    localize: Option<String>,
    initTreeItem: Option<String>,
    handleTreeChanged: Option<String>,
    handleFocusOut: Option<String>,
    handleFocusIn: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-tree {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "defaultSlot": defaultSlot.unwrap_or_default(),
            "expandedIconSlot": expandedIconSlot.unwrap_or_default(),
            "collapsedIconSlot": collapsedIconSlot.unwrap_or_default(),
            "selection": selection.unwrap_or_default(),
            "lastFocusedItem": lastFocusedItem.unwrap_or_default(),
            "mutationObserver": mutationObserver.unwrap_or_default(),
            "clickTarget": clickTarget.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "initTreeItem": initTreeItem.unwrap_or_default(),
            "handleTreeChanged": handleTreeChanged.unwrap_or_default(),
            "handleFocusOut": handleFocusOut.unwrap_or_default(),
            "handleFocusIn": handleFocusIn.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-tree-item`
#[component]
pub fn SlTreeItem(
    dependencies: Option<String>,
    localize: Option<String>,
    indeterminate: Option<bool>,
    isLeaf: Option<bool>,
    loading: Option<bool>,
    selectable: Option<bool>,
    expanded: Option<bool>,
    selected: Option<bool>,
    disabled: Option<bool>,
    lazy: Option<bool>,
    defaultSlot: Option<String>,
    childrenSlot: Option<String>,
    itemElement: Option<String>,
    childrenContainer: Option<String>,
    expandButtonSlot: Option<String>,
    children: Element,
) -> Element {
    rsx! {
        sl-tree-item {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            "dependencies": dependencies.unwrap_or_default(),
            "localize": localize.unwrap_or_default(),
            "indeterminate": indeterminate.unwrap_or_default(),
            "isLeaf": isLeaf.unwrap_or_default(),
            "loading": loading.unwrap_or_default(),
            "selectable": selectable.unwrap_or_default(),
            "expanded": expanded.unwrap_or_default(),
            "selected": selected.unwrap_or_default(),
            "disabled": disabled.unwrap_or_default(),
            "lazy": lazy.unwrap_or_default(),
            "defaultSlot": defaultSlot.unwrap_or_default(),
            "childrenSlot": childrenSlot.unwrap_or_default(),
            "itemElement": itemElement.unwrap_or_default(),
            "childrenContainer": childrenContainer.unwrap_or_default(),
            "expandButtonSlot": expandButtonSlot.unwrap_or_default(),
            {children}
        }
    }
}

/// Dioxus wrapper for `sl-visually-hidden`
#[component]
pub fn SlVisuallyHidden(
    children: Element,
) -> Element {
    rsx! {
        sl-visually-hidden {
            style: "--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);",
            {children}
        }
    }
}

