/// Pane Registry — maps semantic type hashes to human-readable component identifiers.
///
/// When the Studio canvas encounters a `PanePlacement`, it looks up the `component_id`
/// in this registry to determine which Shoelace/Dioxus widget to render.
/// This implements the SolidOS "Pane Dispatcher" pattern from redesign-web-platform.md §5.
use serde::{Deserialize, Serialize};

#[cfg(not(target_arch = "wasm32"))]
fn q42(s: &str) -> Option<u64> {
    Some(qualia_core_db::q_hash(s))
}
#[cfg(target_arch = "wasm32")]
fn q42(_s: &str) -> Option<u64> {
    None
}

/// A registered pane type that the Studio knows how to render.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct PaneDefinition {
    /// Human-readable identifier (e.g., "time-series-chart", "data-ingest-form")
    pub component_id: String,
    /// Display name shown in the sidebar palette
    pub display_name: String,
    /// The Shoelace/Dioxus element tag or custom component name
    pub element_tag: String,
    /// Icon name (Shoelace icon library)
    pub icon: String,
    /// Category for sidebar grouping
    pub category: PaneCategory,
    /// Default grid dimensions when dropped onto canvas
    pub default_w: u8,
    pub default_h: u8,
    /// Optional: semantic type hash this pane is bound to (for auto-dispatch)
    pub rdf_type_hash: Option<u64>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub enum PaneCategory {
    DataDisplay,
    DataInput,
    Layout,
    Media,
    System,
    Computational, // Scientific solvers, numerical methods, domain engines
    Intelligence,  // LLM, LoRA, agent, inference monitoring
    Governance,    // Security, rights, credentials, deontic logic
    Knowledge,     // Ontology, SPARQL, RDF, N3, Solid
    Network,       // P2P, WebTorrent, eBPF, mesh
    Data,          // WAL, provenance, storage, CRDT
}

/// The built-in pane palette available to all users.
/// Extensions can register additional panes at runtime.
pub fn builtin_pane_definitions() -> Vec<PaneDefinition> {
    vec![
        // --- Data Display ---
        PaneDefinition {
            component_id: "card-view".into(),
            display_name: "Card".into(),
            element_tag: "sl-card".into(),
            icon: "card-heading".into(),
            category: PaneCategory::DataDisplay,
            default_w: 4,
            default_h: 3,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "details-view".into(),
            display_name: "Expandable Details".into(),
            element_tag: "sl-details".into(),
            icon: "chevron-expand".into(),
            category: PaneCategory::DataDisplay,
            default_w: 6,
            default_h: 2,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "progress-monitor".into(),
            display_name: "Progress Bar".into(),
            element_tag: "sl-progress-bar".into(),
            icon: "bar-chart-fill".into(),
            category: PaneCategory::DataDisplay,
            default_w: 6,
            default_h: 1,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "badge-indicator".into(),
            display_name: "Badge / Status".into(),
            element_tag: "sl-badge".into(),
            icon: "patch-check".into(),
            category: PaneCategory::DataDisplay,
            default_w: 2,
            default_h: 1,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "rating-widget".into(),
            display_name: "Rating".into(),
            element_tag: "sl-rating".into(),
            icon: "star-half".into(),
            category: PaneCategory::DataDisplay,
            default_w: 4,
            default_h: 1,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "qr-code-display".into(),
            display_name: "QR Code".into(),
            element_tag: "sl-qr-code".into(),
            icon: "qr-code".into(),
            category: PaneCategory::DataDisplay,
            default_w: 3,
            default_h: 3,
            rdf_type_hash: None,
        },
        // --- Data Input ---
        PaneDefinition {
            component_id: "dynamic-form".into(),
            display_name: "SHACL Form".into(),
            element_tag: "qualia-dynamic-form".into(),
            icon: "ui-radios-grid".into(),
            category: PaneCategory::DataInput,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "text-input".into(),
            display_name: "Text Input".into(),
            element_tag: "sl-input".into(),
            icon: "input-cursor-text".into(),
            category: PaneCategory::DataInput,
            default_w: 4,
            default_h: 1,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "text-area".into(),
            display_name: "Text Area".into(),
            element_tag: "sl-textarea".into(),
            icon: "textarea-resize".into(),
            category: PaneCategory::DataInput,
            default_w: 6,
            default_h: 3,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "checkbox-toggle".into(),
            display_name: "Checkbox".into(),
            element_tag: "sl-checkbox".into(),
            icon: "check2-square".into(),
            category: PaneCategory::DataInput,
            default_w: 3,
            default_h: 1,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "switch-toggle".into(),
            display_name: "Switch".into(),
            element_tag: "sl-switch".into(),
            icon: "toggles".into(),
            category: PaneCategory::DataInput,
            default_w: 3,
            default_h: 1,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "select-dropdown".into(),
            display_name: "Select / Dropdown".into(),
            element_tag: "sl-select".into(),
            icon: "menu-button-wide".into(),
            category: PaneCategory::DataInput,
            default_w: 4,
            default_h: 1,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "color-picker".into(),
            display_name: "Color Picker".into(),
            element_tag: "sl-color-picker".into(),
            icon: "palette".into(),
            category: PaneCategory::DataInput,
            default_w: 3,
            default_h: 3,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "range-slider".into(),
            display_name: "Range Slider".into(),
            element_tag: "sl-range".into(),
            icon: "sliders".into(),
            category: PaneCategory::DataInput,
            default_w: 6,
            default_h: 1,
            rdf_type_hash: None,
        },
        // --- Layout ---
        PaneDefinition {
            component_id: "tab-group".into(),
            display_name: "Tab Group".into(),
            element_tag: "sl-tab-group".into(),
            icon: "layout-text-window".into(),
            category: PaneCategory::Layout,
            default_w: 12,
            default_h: 6,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "split-panel".into(),
            display_name: "Split Panel".into(),
            element_tag: "sl-split-panel".into(),
            icon: "layout-split".into(),
            category: PaneCategory::Layout,
            default_w: 12,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "dialog-modal".into(),
            display_name: "Dialog / Modal".into(),
            element_tag: "sl-dialog".into(),
            icon: "window-stack".into(),
            category: PaneCategory::Layout,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "divider".into(),
            display_name: "Divider".into(),
            element_tag: "sl-divider".into(),
            icon: "dash-lg".into(),
            category: PaneCategory::Layout,
            default_w: 12,
            default_h: 1,
            rdf_type_hash: None,
        },
        // --- Media ---
        PaneDefinition {
            component_id: "image-comparer".into(),
            display_name: "Image Comparer".into(),
            element_tag: "sl-image-comparer".into(),
            icon: "images".into(),
            category: PaneCategory::Media,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "carousel".into(),
            display_name: "Carousel".into(),
            element_tag: "sl-carousel".into(),
            icon: "collection-play".into(),
            category: PaneCategory::Media,
            default_w: 8,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "avatar".into(),
            display_name: "Avatar".into(),
            element_tag: "sl-avatar".into(),
            icon: "person-circle".into(),
            category: PaneCategory::Media,
            default_w: 2,
            default_h: 2,
            rdf_type_hash: None,
        },
        // --- System ---
        PaneDefinition {
            component_id: "alert-notification".into(),
            display_name: "Alert / Notification".into(),
            element_tag: "sl-alert".into(),
            icon: "bell".into(),
            category: PaneCategory::System,
            default_w: 6,
            default_h: 2,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "spinner".into(),
            display_name: "Spinner".into(),
            element_tag: "sl-spinner".into(),
            icon: "arrow-clockwise".into(),
            category: PaneCategory::System,
            default_w: 2,
            default_h: 2,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "skeleton-loader".into(),
            display_name: "Skeleton Loader".into(),
            element_tag: "sl-skeleton".into(),
            icon: "layout-wtf".into(),
            category: PaneCategory::System,
            default_w: 6,
            default_h: 2,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "system-diagnostics".into(),
            display_name: "Diagnostics & Telemetry".into(),
            element_tag: "qualia-system-diagnostics".into(),
            icon: "cpu".into(),
            category: PaneCategory::System,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "error-logs".into(),
            display_name: "Error & Audit Logs".into(),
            element_tag: "qualia-error-logs".into(),
            icon: "exclamation-triangle".into(),
            category: PaneCategory::System,
            default_w: 12,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "sensor-data".into(),
            display_name: "Sensor & IoT Stream".into(),
            element_tag: "qualia-sensor-data".into(),
            icon: "activity".into(),
            category: PaneCategory::DataDisplay,
            default_w: 6,
            default_h: 3,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "custom-web-module".into(),
            display_name: "Web Module (RPC/IFrame)".into(),
            element_tag: "qualia-web-module".into(),
            icon: "window-dock".into(),
            category: PaneCategory::System,
            default_w: 8,
            default_h: 6,
            rdf_type_hash: q42("q42:WebModule"),
        },
        // --- Webizen Integrations ---
        PaneDefinition {
            component_id: "web-browser-pane".into(),
            display_name: "Web Browser".into(),
            element_tag: "web-browser-pane".into(),
            icon: "globe2".into(),
            category: PaneCategory::System,
            default_w: 12,
            default_h: 8,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "dialectical-sidebar-pane".into(),
            display_name: "Dialectical Chat Sidebar".into(),
            element_tag: "dialectical-sidebar-pane".into(),
            icon: "chat-left-dots".into(),
            category: PaneCategory::Intelligence,
            default_w: 4,
            default_h: 8,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "cognitive-monitor-pane".into(),
            display_name: "Cognitive Monitor".into(),
            element_tag: "cognitive-monitor-pane".into(),
            icon: "activity".into(),
            category: PaneCategory::Intelligence,
            default_w: 4,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "contextual-workspace".into(),
            display_name: "Context Studio".into(),
            element_tag: "contextual-workspace".into(),
            icon: "diagram-3".into(),
            category: PaneCategory::Layout,
            default_w: 12,
            default_h: 8,
            rdf_type_hash: q42("q42:ContextualWorkspace"),
        },
        PaneDefinition {
            component_id: "neuro-symbolic-chat".into(),
            display_name: "Neuro-Symbolic Chat".into(),
            element_tag: "neuro-symbolic-chat".into(),
            icon: "chat-dots".into(),
            category: PaneCategory::DataInput,
            default_w: 8,
            default_h: 6,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "llm-model-harness".into(),
            display_name: "LLM Model Harness".into(),
            element_tag: "llm-harness".into(),
            icon: "cpu-fill".into(),
            category: PaneCategory::System,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "health-vital-monitor".into(),
            display_name: "Health Vital Monitor".into(),
            element_tag: "health-vital-monitor".into(),
            icon: "heart-pulse".into(),
            category: PaneCategory::DataDisplay,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "personal-ontology-builder".into(),
            display_name: "Personal Ontology Builder".into(),
            element_tag: "personal-ontology-builder".into(),
            icon: "diagram-3".into(),
            category: PaneCategory::DataInput,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "hardware-configurator".into(),
            display_name: "Hardware Configurator".into(),
            element_tag: "hardware-configurator".into(),
            icon: "tools".into(),
            category: PaneCategory::DataInput,
            default_w: 8,
            default_h: 6,
            rdf_type_hash: None,
        },
        // ── Computational ─────────────────────────────────────────────────────
        PaneDefinition {
            component_id: "physics-simulator".into(),
            display_name: "Physics Simulator".into(),
            element_tag: "physics-simulator".into(),
            icon: "lightning-charge".into(),
            category: PaneCategory::Computational,
            default_w: 8,
            default_h: 6,
            rdf_type_hash: q42("q42:PhysicsSimulator"),
        },
        PaneDefinition {
            component_id: "chemistry-modeler".into(),
            display_name: "Chemistry Modeler".into(),
            element_tag: "chemistry-modeler".into(),
            icon: "droplet".into(),
            category: PaneCategory::Computational,
            default_w: 8,
            default_h: 6,
            rdf_type_hash: q42("q42:ChemistryModeler"),
        },
        PaneDefinition {
            component_id: "ode-solver".into(),
            display_name: "ODE & Calculus Lab".into(),
            element_tag: "ode-solver".into(),
            icon: "graph-up".into(),
            category: PaneCategory::Computational,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: q42("q42:OdeSolver"),
        },
        PaneDefinition {
            component_id: "matrix-lab".into(),
            display_name: "Matrix & Linear Algebra".into(),
            element_tag: "matrix-lab".into(),
            icon: "grid-3x3".into(),
            category: PaneCategory::Computational,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: q42("q42:MatrixLab"),
        },
        PaneDefinition {
            component_id: "statistical-analysis".into(),
            display_name: "Statistical Analysis Lab".into(),
            element_tag: "statistical-analysis".into(),
            icon: "bar-chart-line".into(),
            category: PaneCategory::Computational,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: q42("q42:StatisticalAnalysis"),
        },
        PaneDefinition {
            component_id: "bioinformatics-lab".into(),
            display_name: "Bioinformatics Lab".into(),
            element_tag: "bioinformatics-lab".into(),
            icon: "bezier2".into(),
            category: PaneCategory::Computational,
            default_w: 10,
            default_h: 6,
            rdf_type_hash: q42("q42:BioinformaticsLab"),
        },
        PaneDefinition {
            component_id: "qpu-optimizer".into(),
            display_name: "QPU Optimizer".into(),
            element_tag: "qpu-optimizer".into(),
            icon: "cpu".into(),
            category: PaneCategory::Computational,
            default_w: 8,
            default_h: 6,
            rdf_type_hash: q42("q42:QpuOptimizer"),
        },
        PaneDefinition {
            component_id: "quantum-dft".into(),
            display_name: "Quantum DFT Lab".into(),
            element_tag: "quantum-dft".into(),
            icon: "soundwave".into(),
            category: PaneCategory::Computational,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: q42("q42:QuantumDft"),
        },
        PaneDefinition {
            component_id: "qaoa-explorer".into(),
            display_name: "QAOA Explorer".into(),
            element_tag: "qaoa-explorer".into(),
            icon: "sliders".into(),
            category: PaneCategory::Computational,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: q42("q42:QaoaExplorer"),
        },
        PaneDefinition {
            component_id: "portfolio-analyzer".into(),
            display_name: "Portfolio Analyzer".into(),
            element_tag: "portfolio-analyzer".into(),
            icon: "currency-exchange".into(),
            category: PaneCategory::Computational,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: q42("q42:PortfolioAnalyzer"),
        },
        PaneDefinition {
            component_id: "risk-engine".into(),
            display_name: "Risk Engine".into(),
            element_tag: "risk-engine".into(),
            icon: "graph-up-arrow".into(),
            category: PaneCategory::Computational,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: q42("q42:RiskEngine"),
        },
        PaneDefinition {
            component_id: "gbm-simulator".into(),
            display_name: "GBM Simulator".into(),
            element_tag: "gbm-simulator".into(),
            icon: "shuffle".into(),
            category: PaneCategory::Computational,
            default_w: 8,
            default_h: 4,
            rdf_type_hash: q42("q42:GbmSimulator"),
        },
        // ── Intelligence ──────────────────────────────────────────────────────
        PaneDefinition {
            component_id: "llm-harness".into(),
            display_name: "LLM Model Harness".into(),
            element_tag: "llm-harness".into(),
            icon: "cpu-fill".into(),
            category: PaneCategory::Intelligence,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "lora-manager".into(),
            display_name: "LoRA Adapter Manager".into(),
            element_tag: "lora-manager".into(),
            icon: "layers-half".into(),
            category: PaneCategory::Intelligence,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: q42("q42:LoraManager"),
        },
        PaneDefinition {
            component_id: "inference-monitor".into(),
            display_name: "Inference Monitor".into(),
            element_tag: "inference-monitor".into(),
            icon: "activity".into(),
            category: PaneCategory::Intelligence,
            default_w: 8,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "agent-config".into(),
            display_name: "Agent Configuration".into(),
            element_tag: "agent-config".into(),
            icon: "robot".into(),
            category: PaneCategory::Intelligence,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "model-lifecycle".into(),
            display_name: "Model Lifecycle".into(),
            element_tag: "model-lifecycle".into(),
            icon: "arrow-repeat".into(),
            category: PaneCategory::Intelligence,
            default_w: 6,
            default_h: 3,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "qpu-providers".into(),
            display_name: "QPU Provider Manager".into(),
            element_tag: "qpu-providers".into(),
            icon: "cloud-check".into(),
            category: PaneCategory::Intelligence,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        // ── Governance ────────────────────────────────────────────────────────
        PaneDefinition {
            component_id: "agreements-rights".into(),
            display_name: "Agreements & Rights".into(),
            element_tag: "agreements-rights".into(),
            icon: "file-earmark-check".into(),
            category: PaneCategory::Governance,
            default_w: 8,
            default_h: 6,
            rdf_type_hash: q42("q42:AgreementsRights"),
        },
        PaneDefinition {
            component_id: "key-vault-manager".into(),
            display_name: "Key Vault Manager".into(),
            element_tag: "key-vault-manager".into(),
            icon: "key".into(),
            category: PaneCategory::Governance,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: q42("q42:KeyVault"),
        },
        PaneDefinition {
            component_id: "zk-proof-studio".into(),
            display_name: "ZK Proof Studio".into(),
            element_tag: "zk-proof-studio".into(),
            icon: "eye-slash".into(),
            category: PaneCategory::Governance,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: q42("q42:ZkProofStudio"),
        },
        PaneDefinition {
            component_id: "deontic-logic-editor".into(),
            display_name: "Deontic Logic Editor".into(),
            element_tag: "deontic-logic-editor".into(),
            icon: "journal-text".into(),
            category: PaneCategory::Governance,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: q42("q42:DeonticLogicEditor"),
        },
        PaneDefinition {
            component_id: "shacl-validator".into(),
            display_name: "SHACL Validator".into(),
            element_tag: "shacl-validator".into(),
            icon: "check2-all".into(),
            category: PaneCategory::Governance,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: q42("q42:ShaclValidator"),
        },
        // ── Knowledge ─────────────────────────────────────────────────────────
        PaneDefinition {
            component_id: "sparql-explorer".into(),
            display_name: "SPARQL Explorer".into(),
            element_tag: "sparql-explorer".into(),
            icon: "code-slash".into(),
            category: PaneCategory::Knowledge,
            default_w: 10,
            default_h: 6,
            rdf_type_hash: q42("q42:SparqlExplorer"),
        },
        PaneDefinition {
            component_id: "n3-logic-studio".into(),
            display_name: "N3 Logic Studio".into(),
            element_tag: "n3-logic-studio".into(),
            icon: "braces".into(),
            category: PaneCategory::Knowledge,
            default_w: 8,
            default_h: 6,
            rdf_type_hash: q42("q42:N3LogicStudio"),
        },
        PaneDefinition {
            component_id: "rdf-star-editor".into(),
            display_name: "RDF-Star Editor".into(),
            element_tag: "rdf-star-editor".into(),
            icon: "diagram-2".into(),
            category: PaneCategory::Knowledge,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: q42("q42:RdfStarEditor"),
        },
        PaneDefinition {
            component_id: "solid-ldp-browser".into(),
            display_name: "Solid LDP Browser".into(),
            element_tag: "solid-ldp-browser".into(),
            icon: "folder-symlink".into(),
            category: PaneCategory::Knowledge,
            default_w: 8,
            default_h: 6,
            rdf_type_hash: q42("q42:SolidLdpBrowser"),
        },
        PaneDefinition {
            component_id: "nexus-canvas".into(),
            display_name: "Nexus Research Canvas".into(),
            element_tag: "nexus-canvas".into(),
            icon: "radioactive".into(),
            category: PaneCategory::Knowledge,
            default_w: 12,
            default_h: 8,
            rdf_type_hash: q42("q42:NexusCanvas"),
        },
        // ── Network ───────────────────────────────────────────────────────────
        PaneDefinition {
            component_id: "webtorrent-seeder".into(),
            display_name: "WebTorrent Seeder".into(),
            element_tag: "webtorrent-seeder".into(),
            icon: "share".into(),
            category: PaneCategory::Network,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "p2p-dashboard".into(),
            display_name: "P2P Node Dashboard".into(),
            element_tag: "p2p-dashboard".into(),
            icon: "diagram-3-fill".into(),
            category: PaneCategory::Network,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "ebpf-filter-manager".into(),
            display_name: "eBPF Filter Manager".into(),
            element_tag: "ebpf-filter-manager".into(),
            icon: "funnel".into(),
            category: PaneCategory::Network,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "acoustic-ble-mesh".into(),
            display_name: "Acoustic BLE Mesh".into(),
            element_tag: "acoustic-ble-mesh".into(),
            icon: "broadcast".into(),
            category: PaneCategory::Network,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        // ── Data & Storage ────────────────────────────────────────────────────
        PaneDefinition {
            component_id: "wal-inspector".into(),
            display_name: "WAL Inspector".into(),
            element_tag: "wal-inspector".into(),
            icon: "journal-code".into(),
            category: PaneCategory::Data,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "q42-volume-manager".into(),
            display_name: "Q42 Volume Manager".into(),
            element_tag: "q42-volume-manager".into(),
            icon: "database".into(),
            category: PaneCategory::Data,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "provenance-graph".into(),
            display_name: "Provenance Graph".into(),
            element_tag: "provenance-graph".into(),
            icon: "diagram-2-fill".into(),
            category: PaneCategory::Data,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: q42("q42:ProvenanceGraph"),
        },
        PaneDefinition {
            component_id: "storage-driver-config".into(),
            display_name: "Storage Driver Config".into(),
            element_tag: "storage-driver-config".into(),
            icon: "hdd-stack".into(),
            category: PaneCategory::Data,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        // ── Developer Tools ───────────────────────────────────────────────────
        PaneDefinition {
            component_id: "mcp-inspector".into(),
            display_name: "MCP Tool Inspector".into(),
            element_tag: "mcp-inspector".into(),
            icon: "plugin".into(),
            category: PaneCategory::System,
            default_w: 8,
            default_h: 6,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "benchmark-harness".into(),
            display_name: "Benchmark Harness".into(),
            element_tag: "benchmark-harness".into(),
            icon: "stopwatch".into(),
            category: PaneCategory::System,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "cli-bridge".into(),
            display_name: "CLI Bridge".into(),
            element_tag: "cli-bridge".into(),
            icon: "terminal".into(),
            category: PaneCategory::System,
            default_w: 8,
            default_h: 5,
            rdf_type_hash: None,
        },
        PaneDefinition {
            component_id: "extension-bus".into(),
            display_name: "Extension Bus".into(),
            element_tag: "extension-bus".into(),
            icon: "puzzle".into(),
            category: PaneCategory::System,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: None,
        },
        // ── Medical ───────────────────────────────────────────────────────────
        PaneDefinition {
            component_id: "clinical-risk-scorer".into(),
            display_name: "Clinical Risk Scorer".into(),
            element_tag: "clinical-risk-scorer".into(),
            icon: "clipboard2-pulse".into(),
            category: PaneCategory::DataDisplay,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: q42("q42:ClinicalRiskScorer"),
        },
        PaneDefinition {
            component_id: "dicom-viewer".into(),
            display_name: "DICOM Viewer".into(),
            element_tag: "dicom-viewer".into(),
            icon: "image-alt".into(),
            category: PaneCategory::DataDisplay,
            default_w: 8,
            default_h: 6,
            rdf_type_hash: q42("q42:DicomViewer"),
        },
        PaneDefinition {
            component_id: "comorbidity-analyzer".into(),
            display_name: "Comorbidity Analyzer".into(),
            element_tag: "comorbidity-analyzer".into(),
            icon: "shield-plus".into(),
            category: PaneCategory::DataDisplay,
            default_w: 6,
            default_h: 4,
            rdf_type_hash: q42("q42:ComorbidityAnalyzer"),
        },
    ]
}

/// Look up a pane definition by component_id.
pub fn find_pane(component_id: &str) -> Option<PaneDefinition> {
    builtin_pane_definitions()
        .into_iter()
        .find(|p| p.component_id == component_id)
}

/// Category display name for sidebar grouping.
pub fn category_label(cat: &PaneCategory) -> &'static str {
    match cat {
        PaneCategory::DataDisplay => "Data Display",
        PaneCategory::DataInput => "Data Input",
        PaneCategory::Layout => "Layout",
        PaneCategory::Media => "Media",
        PaneCategory::System => "System",
        PaneCategory::Computational => "Computational",
        PaneCategory::Intelligence => "AI & Inference",
        PaneCategory::Governance => "Governance",
        PaneCategory::Knowledge => "Knowledge",
        PaneCategory::Network => "Network",
        PaneCategory::Data => "Data & Storage",
    }
}
